server:
    port: 8002

spring:
    application:
        name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #表示自己注册进eureka server
    fetch-registry: true #是否从eureka server抓取已有的注册信息，默认为true，！！单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eurake,http://eureka7001.com:7001/eureka #集群